import {
  User,
  Club,
  Event,
  Task,
  TaskDependency,
  Volunteer,
  Meeting,
  MeetingActionItem,
  Document,
  DocumentChunk,
  Risk,
  Announcement,
  Notification,
  AuditLog,
  AIToolCall,
  UserRole,
} from "@/types";

// Static Users
export const SEED_USERS: User[] = [
  {
    id: "usr-prins",
    name: "Prins Patel",
    email: "prins@syntaxsquad.edu",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Prins",
    role: "admin",
    created_at: "2026-08-01T10:00:00Z",
  },
  {
    id: "usr-jay",
    name: "Jay Shah",
    email: "jay.shah@syntaxsquad.edu",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jay",
    role: "organizer",
    created_at: "2026-08-05T11:00:00Z",
  },
  {
    id: "usr-priya",
    name: "Priya Mehta",
    email: "priya.mehta@syntaxsquad.edu",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Priya",
    role: "organizer",
    created_at: "2026-08-06T09:30:00Z",
  },
  {
    id: "usr-rahul",
    name: "Rahul Sharma",
    email: "rahul.sharma@syntaxsquad.edu",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Rahul",
    role: "volunteer",
    created_at: "2026-08-10T14:00:00Z",
  },
  {
    id: "usr-ananya",
    name: "Ananya Iyer",
    email: "ananya.iyer@syntaxsquad.edu",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ananya",
    role: "volunteer",
    created_at: "2026-08-11T12:00:00Z",
  },
  {
    id: "usr-dev",
    name: "Dev Joshi",
    email: "dev.joshi@syntaxsquad.edu",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Dev",
    role: "volunteer",
    created_at: "2026-08-12T08:45:00Z",
  },
  {
    id: "usr-sneha",
    name: "Sneha Reddy",
    email: "sneha.reddy@syntaxsquad.edu",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sneha",
    role: "volunteer",
    created_at: "2026-08-12T16:15:00Z",
  },
  {
    id: "usr-aarav",
    name: "Aarav Gupta",
    email: "aarav.gupta@syntaxsquad.edu",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Aarav",
    role: "volunteer",
    created_at: "2026-08-14T10:20:00Z",
  },
  {
    id: "usr-riya",
    name: "Riya Verma",
    email: "riya.verma@syntaxsquad.edu",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Riya",
    role: "volunteer",
    created_at: "2026-08-15T11:10:00Z",
  },
  {
    id: "usr-karan",
    name: "Karan Malhotra",
    email: "karan.m@syntaxsquad.edu",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Karan",
    role: "volunteer",
    created_at: "2026-08-15T13:30:00Z",
  },
  {
    id: "usr-tanvi",
    name: "Tanvi Saxena",
    email: "tanvi.s@syntaxsquad.edu",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Tanvi",
    role: "volunteer",
    created_at: "2026-08-16T15:00:00Z",
  },
  {
    id: "usr-rohit",
    name: "Rohit Nair",
    email: "rohit.nair@syntaxsquad.edu",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Rohit",
    role: "volunteer",
    created_at: "2026-08-17T09:00:00Z",
  },
  {
    id: "usr-isha",
    name: "Isha Kapoor",
    email: "isha.k@syntaxsquad.edu",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Isha",
    role: "volunteer",
    created_at: "2026-08-17T11:45:00Z",
  },
  {
    id: "usr-vivek",
    name: "Vivek Deshmukh",
    email: "vivek.d@syntaxsquad.edu",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Vivek",
    role: "volunteer",
    created_at: "2026-08-18T14:20:00Z",
  },
  {
    id: "usr-pooja",
    name: "Pooja Hegde",
    email: "pooja.h@syntaxsquad.edu",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Pooja",
    role: "volunteer",
    created_at: "2026-08-19T10:15:00Z",
  },
  {
    id: "usr-manish",
    name: "Manish Tiwari",
    email: "manish.t@syntaxsquad.edu",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Manish",
    role: "volunteer",
    created_at: "2026-08-20T16:40:00Z",
  },
  {
    id: "usr-neha",
    name: "Neha Sen",
    email: "neha.sen@syntaxsquad.edu",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Neha",
    role: "volunteer",
    created_at: "2026-08-21T09:10:00Z",
  },
  {
    id: "usr-aditya",
    name: "Aditya Roy",
    email: "aditya.roy@syntaxsquad.edu",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Aditya",
    role: "volunteer",
    created_at: "2026-08-21T13:25:00Z",
  },
  {
    id: "usr-kavita",
    name: "Kavita Rao",
    email: "kavita.rao@syntaxsquad.edu",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Kavita",
    role: "volunteer",
    created_at: "2026-08-22T10:50:00Z",
  },
  {
    id: "usr-siddharth",
    name: "Siddharth Jain",
    email: "sid.jain@syntaxsquad.edu",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sid",
    role: "volunteer",
    created_at: "2026-08-23T15:10:00Z",
  },
  {
    id: "usr-divya",
    name: "Divya Nambiar",
    email: "divya.n@syntaxsquad.edu",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Divya",
    role: "volunteer",
    created_at: "2026-08-24T11:35:00Z",
  },
  {
    id: "usr-arjun",
    name: "Arjun Pillai",
    email: "arjun.p@syntaxsquad.edu",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Arjun",
    role: "volunteer",
    created_at: "2026-08-25T14:15:00Z",
  },
  {
    id: "usr-meera",
    name: "Meera Chawla",
    email: "meera.c@syntaxsquad.edu",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Meera",
    role: "volunteer",
    created_at: "2026-08-26T08:50:00Z",
  },
  {
    id: "usr-simran",
    name: "Simran Kaur",
    email: "simran.k@syntaxsquad.edu",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Simran",
    role: "member",
    created_at: "2026-08-27T17:00:00Z",
  },
];

// Seed Club
export const SEED_CLUB: Club = {
  id: "club-syntax-squad",
  name: "Syntax Squad / Tech Club",
  description: "Premier collegiate technology, coding and innovation society.",
  created_by: "usr-prins",
  created_at: "2026-07-01T00:00:00Z",
};

// Seed Event
export const SEED_EVENT: Event = {
  id: "event-techfest-2026",
  club_id: "club-syntax-squad",
  name: "LJ TechFest 2026",
  description: "Annual flagship technology symposium hosting 500 participants across hackathons, robotics arenas, AI bootcamps, and executive keynote panels.",
  start_at: "2026-10-24T09:00:00Z",
  end_at: "2026-10-26T18:00:00Z",
  venue: "Grand Auditorium & Engineering Hall B",
  status: "active",
  budget: 15000,
  created_by: "usr-prins",
  created_at: "2026-08-01T00:00:00Z",
};

// 24 Volunteers with realistic skills and workloads
export const SEED_VOLUNTEERS: Volunteer[] = [
  {
    id: "vol-1",
    club_id: "club-syntax-squad",
    user_id: "usr-rahul",
    skills: ["Venue Coordination", "Stage Rigging", "AV Hardware", "Vendor Negotiation"],
    availability: "overloaded",
    notes: "Assigned 7 critical tasks including Auditorium Booking. Highly strained.",
    workloadScore: 92,
  },
  {
    id: "vol-2",
    club_id: "club-syntax-squad",
    user_id: "usr-ananya",
    skills: ["Web Dev", "Next.js", "Tailwind CSS", "Registration Portal"],
    availability: "available",
    notes: "Completed registration frontend mockups. Ready for API integration.",
    workloadScore: 40,
  },
  {
    id: "vol-3",
    club_id: "club-syntax-squad",
    user_id: "usr-dev",
    skills: ["Python", "FastAPI", "Database Architecture", "Discord Bot"],
    availability: "available",
    notes: "Managing automated check-in and QR ticket validation microservice.",
    workloadScore: 35,
  },
  {
    id: "vol-4",
    club_id: "club-syntax-squad",
    user_id: "usr-sneha",
    skills: ["Graphic Design", "Figma", "Branding", "Badge Printing"],
    availability: "busy",
    notes: "Finalizing participant badge templates and banner prints.",
    workloadScore: 70,
  },
  {
    id: "vol-5",
    club_id: "club-syntax-squad",
    user_id: "usr-aarav",
    skills: ["Sponsorship Outreach", "Budgeting", "Corporate Liaison"],
    availability: "busy",
    notes: "Chasing 3 tier-1 tech sponsors. Needs follow-up authorization.",
    workloadScore: 65,
  },
  {
    id: "vol-6",
    club_id: "club-syntax-squad",
    user_id: "usr-riya",
    skills: ["Social Media", "Reels", "Instagram", "Copywriting"],
    availability: "available",
    notes: "Teaser video launched. Planning speaker announcement carousel.",
    workloadScore: 45,
  },
  {
    id: "vol-7",
    club_id: "club-syntax-squad",
    user_id: "usr-karan",
    skills: ["Catering", "Hospitality", "VIP Escort", "Logistics"],
    availability: "available",
    notes: "Submitted lunch and high-tea quotation from campus caterer.",
    workloadScore: 30,
  },
  {
    id: "vol-8",
    club_id: "club-syntax-squad",
    user_id: "usr-tanvi",
    skills: ["Security", "Crowd Control", "Fire Safety", "First Aid"],
    availability: "available",
    notes: "Coordinating with campus security for emergency exit protocols.",
    workloadScore: 25,
  },
  {
    id: "vol-9",
    club_id: "club-syntax-squad",
    user_id: "usr-rohit",
    skills: ["Audio Systems", "Acoustics", "DJ Equipment", "Live Streaming"],
    availability: "available",
    notes: "Awaiting auditorium access for audio decibel check.",
    workloadScore: 20,
  },
  {
    id: "vol-10",
    club_id: "club-syntax-squad",
    user_id: "usr-isha",
    skills: ["Robotics Arena", "Arduino", "Track Calibration", "Safety Fencing"],
    availability: "busy",
    notes: "Constructing obstacle race arena in Engineering Hall B.",
    workloadScore: 60,
  },
  {
    id: "vol-11",
    club_id: "club-syntax-squad",
    user_id: "usr-vivek",
    skills: ["Hackathon Mentorship", "Git", "API Keys", "Judging Matrix"],
    availability: "available",
    notes: "Prepared GitHub classroom repo template for 24hr hackathon.",
    workloadScore: 30,
  },
  {
    id: "vol-12",
    club_id: "club-syntax-squad",
    user_id: "usr-pooja",
    skills: ["Guest Speaker Travel", "Hotel Booking", "Airport Pickup"],
    availability: "available",
    notes: "Confirmed flight itineraries for 2 keynote speakers.",
    workloadScore: 40,
  },
  {
    id: "vol-13",
    club_id: "club-syntax-squad",
    user_id: "usr-manish",
    skills: ["Network Infrastructure", "Wi-Fi Router Setup", "Cat6 Cabling"],
    availability: "busy",
    notes: "Campus IT granted 1 Gbps dedicated pipe for hackathon hall.",
    workloadScore: 55,
  },
  {
    id: "vol-14",
    club_id: "club-syntax-squad",
    user_id: "usr-neha",
    skills: ["Photography", "Videography", "Drone Filming"],
    availability: "available",
    notes: "Equipment checklist approved; batteries and SD cards reserved.",
    workloadScore: 20,
  },
  {
    id: "vol-15",
    club_id: "club-syntax-squad",
    user_id: "usr-aditya",
    skills: ["Swag Bag Curation", "T-Shirt Sizing", "Lanyard Procurement"],
    availability: "busy",
    notes: "Samples received from vendor; awaiting final headcount approval.",
    workloadScore: 60,
  },
  {
    id: "vol-16",
    club_id: "club-syntax-squad",
    user_id: "usr-kavita",
    skills: ["Help Desk", "Attendee Queries", "Lost & Found"],
    availability: "available",
    notes: "Prepared FAQ sheet for registration counter volunteers.",
    workloadScore: 15,
  },
  {
    id: "vol-17",
    club_id: "club-syntax-squad",
    user_id: "usr-siddharth",
    skills: ["Certificate Generation", "Digital Badging", "Python Automation"],
    availability: "available",
    notes: "Canvas API certificate template tested with 100 mock names.",
    workloadScore: 25,
  },
  {
    id: "vol-18",
    club_id: "club-syntax-squad",
    user_id: "usr-divya",
    skills: ["Stage Anchoring", "Opening Ceremony Host", "Debate Moderation"],
    availability: "available",
    notes: "Drafted anchor script for inauguration ceremony.",
    workloadScore: 35,
  },
  {
    id: "vol-19",
    club_id: "club-syntax-squad",
    user_id: "usr-arjun",
    skills: ["Electrical Load Testing", "Backup Generator", "UPS Setup"],
    availability: "available",
    notes: "Secured 40kVA standby diesel generator permit.",
    workloadScore: 40,
  },
  {
    id: "vol-20",
    club_id: "club-syntax-squad",
    user_id: "usr-meera",
    skills: ["Trophy Sourcing", "Medals", "Memento Presentation"],
    availability: "available",
    notes: "Selected 1st, 2nd, 3rd place laser-engraved acrylic trophies.",
    workloadScore: 30,
  },
  {
    id: "vol-21",
    club_id: "club-syntax-squad",
    user_id: "usr-simran",
    skills: ["Registration Desk Support", "Barcode Scanning"],
    availability: "available",
    notes: "Assigned to morning shift registration booth.",
    workloadScore: 10,
  },
  {
    id: "vol-22",
    club_id: "club-syntax-squad",
    user_id: "usr-jay",
    skills: ["Overall Event Lead", "Budget Control", "Administrative Approvals"],
    availability: "busy",
    notes: "Supervising core team and coordinating with university leadership.",
    workloadScore: 75,
  },
  {
    id: "vol-23",
    club_id: "club-syntax-squad",
    user_id: "usr-priya",
    skills: ["Marketing Lead", "PR Outreach", "Sponsorship Closing"],
    availability: "busy",
    notes: "Managing social campaigns, press releases and partner colleges.",
    workloadScore: 80,
  },
  {
    id: "vol-24",
    club_id: "club-syntax-squad",
    user_id: "usr-prins",
    skills: ["Faculty Liaison", "Club President", "Platform Administrator"],
    availability: "busy",
    notes: "Executive signoffs, budget allocations and administrative compliance.",
    workloadScore: 70,
  },
];

// 42 Realistic Tasks with complete metadata & dependency chain
export const SEED_TASKS: Task[] = [
  // The Critical Dependency Chain (Tasks 1 -> 2 -> 3 -> 4)
  {
    id: "task-01",
    event_id: "event-techfest-2026",
    title: "Confirm Grand Auditorium Booking & Dean Signoff",
    description: "Obtain the formal stamped approval letter from Dean Office and key handover for the main auditorium.",
    owner_id: "usr-rahul",
    status: "blocked",
    priority: "critical",
    due_at: "2026-09-17T17:00:00Z", // 2 days overdue
    created_by: "usr-jay",
    created_at: "2026-09-10T10:00:00Z",
    updated_at: "2026-09-18T16:00:00Z",
    dependencies: [],
    dependents: ["task-02"],
  },
  {
    id: "task-02",
    event_id: "event-techfest-2026",
    title: "Finalize Stage Rigging & Lighting Rig Layout",
    description: "Hang overhead spotlights, center projector truss, and calibrate LED backdrop screen.",
    owner_id: "usr-rahul",
    status: "todo",
    priority: "high",
    due_at: "2026-09-22T18:00:00Z",
    created_by: "usr-jay",
    created_at: "2026-09-10T10:05:00Z",
    updated_at: "2026-09-10T10:05:00Z",
    dependencies: ["task-01"],
    dependents: ["task-03"],
  },
  {
    id: "task-03",
    event_id: "event-techfest-2026",
    title: "Sound Check & Wireless Mic Frequency Tuning",
    description: "Test 6 podium mics, 4 wireless lavaliers, and calibrate line-array acoustics in the main hall.",
    owner_id: "usr-rohit",
    status: "todo",
    priority: "high",
    due_at: "2026-09-24T15:00:00Z",
    created_by: "usr-jay",
    created_at: "2026-09-10T10:10:00Z",
    updated_at: "2026-09-10T10:10:00Z",
    dependencies: ["task-02"],
    dependents: ["task-04"],
  },
  {
    id: "task-04",
    event_id: "event-techfest-2026",
    title: "Full Dress Rehearsal & Speaker Walkthrough",
    description: "Complete dry run of the inaugural ceremony, anchor introductions, and keynote slide decks.",
    owner_id: "usr-priya",
    status: "backlog",
    priority: "medium",
    due_at: "2026-09-26T17:00:00Z",
    created_by: "usr-jay",
    created_at: "2026-09-10T10:15:00Z",
    updated_at: "2026-09-10T10:15:00Z",
    dependencies: ["task-03"],
    dependents: [],
  },

  // Other Overdue & Critical Tasks
  {
    id: "task-05",
    event_id: "event-techfest-2026",
    title: "Submit Tier-1 Tech Sponsor Proposal Packets",
    description: "Send formal ₹5,00,000 Title Sponsor proposal deck to Google Cloud, GitHub and RedBull representatives.",
    owner_id: "usr-aarav",
    status: "in_progress",
    priority: "critical",
    due_at: "2026-09-17T12:00:00Z", // Overdue
    created_by: "usr-priya",
    created_at: "2026-09-08T11:00:00Z",
    updated_at: "2026-09-18T14:30:00Z",
  },
  {
    id: "task-06",
    event_id: "event-techfest-2026",
    title: "Pay Catering Vendor Advance Deposit",
    description: "Disburse 30% advance ($1,500) to GreenPlate Hospitality for 500 meal coupons and high-tea.",
    owner_id: "usr-karan",
    status: "todo",
    priority: "high",
    due_at: "2026-09-18T17:00:00Z", // 1 day overdue
    created_by: "usr-jay",
    created_at: "2026-09-09T09:00:00Z",
    updated_at: "2026-09-18T09:00:00Z",
  },

  // Overloaded Rahul Sharma Tasks
  {
    id: "task-07",
    event_id: "event-techfest-2026",
    title: "Procure 30 Heavy Extension Boards & Surge Protectors",
    description: "Obtain 16A spike guards for hackathon participant tables.",
    owner_id: "usr-rahul",
    status: "in_progress",
    priority: "medium",
    due_at: "2026-09-22T14:00:00Z",
    created_by: "usr-jay",
    created_at: "2026-09-11T10:00:00Z",
    updated_at: "2026-09-15T11:00:00Z",
  },
  {
    id: "task-08",
    event_id: "event-techfest-2026",
    title: "Inspect Air Conditioning in Engineering Hall B",
    description: "Ensure HVAC blowers operate continuously under heavy thermal load.",
    owner_id: "usr-rahul",
    status: "todo",
    priority: "medium",
    due_at: "2026-09-23T11:00:00Z",
    created_by: "usr-jay",
    created_at: "2026-09-11T10:30:00Z",
    updated_at: "2026-09-11T10:30:00Z",
  },
  {
    id: "task-09",
    event_id: "event-techfest-2026",
    title: "Deliver Podium Banners to Printing Press",
    description: "Provide high-res SVG vectors to MasterGraphics for vinyl printing.",
    owner_id: "usr-rahul",
    status: "todo",
    priority: "medium",
    due_at: "2026-09-21T16:00:00Z",
    created_by: "usr-sneha",
    created_at: "2026-09-12T09:00:00Z",
    updated_at: "2026-09-12T09:00:00Z",
  },
  {
    id: "task-10",
    event_id: "event-techfest-2026",
    title: "Supervise Stage Carpet & Table Skirting Installation",
    description: "Ensure stage presentation tables are draped according to corporate protocol.",
    owner_id: "usr-rahul",
    status: "backlog",
    priority: "low",
    due_at: "2026-09-25T12:00:00Z",
    created_by: "usr-jay",
    created_at: "2026-09-12T14:00:00Z",
    updated_at: "2026-09-12T14:00:00Z",
  },
  {
    id: "task-11",
    event_id: "event-techfest-2026",
    title: "Manage Green Room Access & Speaker Refreshments",
    description: "Coordinate access keys and bottled water for VIP guest green rooms.",
    owner_id: "usr-rahul",
    status: "backlog",
    priority: "low",
    due_at: "2026-09-26T08:00:00Z",
    created_by: "usr-pooja",
    created_at: "2026-09-12T15:00:00Z",
    updated_at: "2026-09-12T15:00:00Z",
  },

  // Additional Realistic Tasks across Statuses
  {
    id: "task-12",
    event_id: "event-techfest-2026",
    title: "Publish Registration Portal on Next.js",
    description: "Deploy registration frontend to Vercel with Stripe / Razorpay webhook handling.",
    owner_id: "usr-ananya",
    status: "in_progress",
    priority: "high",
    due_at: "2026-09-20T23:59:00Z",
    created_by: "usr-jay",
    created_at: "2026-09-05T10:00:00Z",
    updated_at: "2026-09-18T18:00:00Z",
  },
  {
    id: "task-13",
    event_id: "event-techfest-2026",
    title: "Design Instagram Teaser Video & Stories",
    description: "Create 9:16 vertical motion reel announcing ₹2,50,000 hackathon prize pool.",
    owner_id: "usr-riya",
    status: "review",
    priority: "high",
    due_at: "2026-09-20T12:00:00Z",
    created_by: "usr-priya",
    created_at: "2026-09-14T11:00:00Z",
    updated_at: "2026-09-18T15:00:00Z",
  },
  {
    id: "task-14",
    event_id: "event-techfest-2026",
    title: "Setup PostgreSQL Schema & Discord OAuth for Hackers",
    description: "Database backend for storing 500 team profiles, submissions and judge scores.",
    owner_id: "usr-dev",
    status: "done",
    priority: "high",
    due_at: "2026-09-15T18:00:00Z",
    created_by: "usr-prins",
    created_at: "2026-09-01T10:00:00Z",
    updated_at: "2026-09-14T20:00:00Z",
  },
  {
    id: "task-15",
    event_id: "event-techfest-2026",
    title: "Design Participant ID Cards & QR Badges",
    description: "Custom printable badge template with hackathon track, team name, and QR check-in.",
    owner_id: "usr-sneha",
    status: "done",
    priority: "medium",
    due_at: "2026-09-16T18:00:00Z",
    created_by: "usr-jay",
    created_at: "2026-09-07T09:00:00Z",
    updated_at: "2026-09-16T17:30:00Z",
  },
  {
    id: "task-16",
    event_id: "event-techfest-2026",
    title: "Order 500 Custom Event Lanyards & Stickers",
    description: "Silkscreen satin lanyards with LJ TechFest logo and die-cut tech stickers.",
    owner_id: "usr-aditya",
    status: "done",
    priority: "medium",
    due_at: "2026-09-12T14:00:00Z",
    created_by: "usr-jay",
    created_at: "2026-09-02T10:00:00Z",
    updated_at: "2026-09-11T16:00:00Z",
  },
  {
    id: "task-17",
    event_id: "event-techfest-2026",
    title: "Build RoboWars Steel Perimeter Fencing",
    description: "Assemble 6mm polycarbonate and slotted angle frame for combat robotics arena.",
    owner_id: "usr-isha",
    status: "in_progress",
    priority: "high",
    due_at: "2026-09-24T18:00:00Z",
    created_by: "usr-jay",
    created_at: "2026-09-10T12:00:00Z",
    updated_at: "2026-09-17T16:00:00Z",
  },
  {
    id: "task-18",
    event_id: "event-techfest-2026",
    title: "Test Wi-Fi Access Points for 500 Concurrent Devices",
    description: "Stress test 10 Cisco Meraki access points in Engineering Hall B with mock traffic.",
    owner_id: "usr-manish",
    status: "in_progress",
    priority: "high",
    due_at: "2026-09-23T17:00:00Z",
    created_by: "usr-prins",
    created_at: "2026-09-08T14:00:00Z",
    updated_at: "2026-09-18T11:00:00Z",
  },
  {
    id: "task-19",
    event_id: "event-techfest-2026",
    title: "Obtain Campus Ambulance & First Aid Station Permit",
    description: "Arrange certified paramedic team and emergency medical kit on standby for 48 hours.",
    owner_id: "usr-tanvi",
    status: "todo",
    priority: "high",
    due_at: "2026-09-25T12:00:00Z",
    created_by: "usr-jay",
    created_at: "2026-09-12T11:00:00Z",
    updated_at: "2026-09-12T11:00:00Z",
  },
  {
    id: "task-20",
    event_id: "event-techfest-2026",
    title: "Book Hotel Suites for 3 Keynote Speakers",
    description: "Reserve 3 executive suites at Marriott Courtyard from Oct 23 to Oct 27.",
    owner_id: "usr-pooja",
    status: "done",
    priority: "medium",
    due_at: "2026-09-15T16:00:00Z",
    created_by: "usr-priya",
    created_at: "2026-09-05T15:00:00Z",
    updated_at: "2026-09-14T19:00:00Z",
  },
  {
    id: "task-21",
    event_id: "event-techfest-2026",
    title: "Draft Hackathon Judging Rubric & Scoring Weights",
    description: "Define criteria: Innovation (30%), Technical Execution (30%), Impact (20%), Pitch (20%).",
    owner_id: "usr-vivek",
    status: "review",
    priority: "medium",
    due_at: "2026-09-21T18:00:00Z",
    created_by: "usr-prins",
    created_at: "2026-09-12T16:00:00Z",
    updated_at: "2026-09-18T10:00:00Z",
  },
  {
    id: "task-22",
    event_id: "event-techfest-2026",
    title: "Confirm Laser Engraving for 12 Winners Trophies",
    description: "Provide exact winner category wording to trophy vendor.",
    owner_id: "usr-meera",
    status: "todo",
    priority: "low",
    due_at: "2026-09-25T14:00:00Z",
    created_by: "usr-jay",
    created_at: "2026-09-14T14:00:00Z",
    updated_at: "2026-09-14T14:00:00Z",
  },
  {
    id: "task-23",
    event_id: "event-techfest-2026",
    title: "Setup Standby Diesel Generator Fuel Tank",
    description: "Ensure 200 liters of diesel delivered and circuit transfer switch tested.",
    owner_id: "usr-arjun",
    status: "todo",
    priority: "high",
    due_at: "2026-09-24T12:00:00Z",
    created_by: "usr-jay",
    created_at: "2026-09-15T10:00:00Z",
    updated_at: "2026-09-15T10:00:00Z",
  },
  {
    id: "task-24",
    event_id: "event-techfest-2026",
    title: "Finalize Master Anchor Script for Opening Ceremony",
    description: "Prepare teleprompter cues, guest speaker bios, and sponsor acknowledgements.",
    owner_id: "usr-divya",
    status: "in_progress",
    priority: "medium",
    due_at: "2026-09-23T16:00:00Z",
    created_by: "usr-priya",
    created_at: "2026-09-13T11:00:00Z",
    updated_at: "2026-09-18T13:00:00Z",
  },
  {
    id: "task-25",
    event_id: "event-techfest-2026",
    title: "Automate Participation Certificates in Canvas API",
    description: "Generate PDF certificates with cryptographic verification hash for 500 attendees.",
    owner_id: "usr-siddharth",
    status: "todo",
    priority: "low",
    due_at: "2026-09-27T18:00:00Z",
    created_by: "usr-dev",
    created_at: "2026-09-15T15:00:00Z",
    updated_at: "2026-09-15T15:00:00Z",
  },
  {
    id: "task-26",
    event_id: "event-techfest-2026",
    title: "Distribute Registration Volunteer Shift Roster",
    description: "Schedule 12 volunteers across 3 shifts for morning badge issuance.",
    owner_id: "usr-kavita",
    status: "review",
    priority: "medium",
    due_at: "2026-09-22T12:00:00Z",
    created_by: "usr-jay",
    created_at: "2026-09-16T10:00:00Z",
    updated_at: "2026-09-18T14:00:00Z",
  },
  {
    id: "task-27",
    event_id: "event-techfest-2026",
    title: "Procure Red Carpet & Stage Flowers for Inauguration",
    description: "Order 50-meter red carpet runner and ceremonial potted plants for stage border.",
    owner_id: "usr-karan",
    status: "todo",
    priority: "low",
    due_at: "2026-09-25T18:00:00Z",
    created_by: "usr-jay",
    created_at: "2026-09-16T14:00:00Z",
    updated_at: "2026-09-16T14:00:00Z",
  },
  {
    id: "task-28",
    event_id: "event-techfest-2026",
    title: "Schedule Campus Security Briefing on Parking & Access",
    description: "Designate VIP parking bays and bus drop-off points with campus security chief.",
    owner_id: "usr-tanvi",
    status: "todo",
    priority: "medium",
    due_at: "2026-09-23T10:00:00Z",
    created_by: "usr-jay",
    created_at: "2026-09-16T16:00:00Z",
    updated_at: "2026-09-16T16:00:00Z",
  },
  {
    id: "task-29",
    event_id: "event-techfest-2026",
    title: "Assemble Swag Bag Goodie Bundles",
    description: "Pack 500 canvas tote bags with notebook, sticker pack, pen, and sponsor coupons.",
    owner_id: "usr-aditya",
    status: "backlog",
    priority: "low",
    due_at: "2026-09-25T20:00:00Z",
    created_by: "usr-priya",
    created_at: "2026-09-17T09:00:00Z",
    updated_at: "2026-09-17T09:00:00Z",
  },
  {
    id: "task-30",
    event_id: "event-techfest-2026",
    title: "Configure Live Stream Camera Switched Feed",
    description: "Connect 3 Sony FX3 cameras to Blackmagic ATEM Mini Pro for YouTube broadcast.",
    owner_id: "usr-neha",
    status: "todo",
    priority: "medium",
    due_at: "2026-09-24T16:00:00Z",
    created_by: "usr-rohit",
    created_at: "2026-09-17T11:00:00Z",
    updated_at: "2026-09-17T11:00:00Z",
  },
  {
    id: "task-31",
    event_id: "event-techfest-2026",
    title: "Draft Press Release for City Newspapers",
    description: "Circulate press release highlighting ₹10 Lakhs innovation funding and 50 partner colleges.",
    owner_id: "usr-priya",
    status: "in_progress",
    priority: "medium",
    due_at: "2026-09-22T17:00:00Z",
    created_by: "usr-prins",
    created_at: "2026-09-17T14:00:00Z",
    updated_at: "2026-09-18T16:30:00Z",
  },
  {
    id: "task-32",
    event_id: "event-techfest-2026",
    title: "Publish Discord Code of Conduct Rules",
    description: "Post server moderation rules, anti-harassment guidelines, and reporting bot.",
    owner_id: "usr-dev",
    status: "done",
    priority: "low",
    due_at: "2026-09-15T12:00:00Z",
    created_by: "usr-prins",
    created_at: "2026-09-10T09:00:00Z",
    updated_at: "2026-09-15T11:45:00Z",
  },
  {
    id: "task-33",
    event_id: "event-techfest-2026",
    title: "Coordinate Morning Breakfast & Coffee Stations",
    description: "Setup 4 tea/coffee urns and breakfast counters for 500 hackers at 8:00 AM.",
    owner_id: "usr-karan",
    status: "todo",
    priority: "medium",
    due_at: "2026-09-26T07:30:00Z",
    created_by: "usr-jay",
    created_at: "2026-09-17T16:00:00Z",
    updated_at: "2026-09-17T16:00:00Z",
  },
  {
    id: "task-34",
    event_id: "event-techfest-2026",
    title: "Test Midnight Snack Delivery Window (1:00 AM)",
    description: "Contract delivery of 500 samosas and energy drinks for overnight hackers.",
    owner_id: "usr-karan",
    status: "backlog",
    priority: "low",
    due_at: "2026-09-27T01:00:00Z",
    created_by: "usr-jay",
    created_at: "2026-09-18T10:00:00Z",
    updated_at: "2026-09-18T10:00:00Z",
  },
  {
    id: "task-35",
    event_id: "event-techfest-2026",
    title: "Calibrate RoboWars Remote Kill-Switch Frequencies",
    description: "Inspect 2.4GHz fail-safe modules for 30 combat robots to prevent runaway hazards.",
    owner_id: "usr-isha",
    status: "todo",
    priority: "high",
    due_at: "2026-09-25T17:00:00Z",
    created_by: "usr-jay",
    created_at: "2026-09-18T11:30:00Z",
    updated_at: "2026-09-18T11:30:00Z",
  },
  {
    id: "task-36",
    event_id: "event-techfest-2026",
    title: "Review Keynote Slide Deck Font Embedding & Videos",
    description: "Test keynote slide transitions on 4K laser projector to avoid codec errors.",
    owner_id: "usr-sneha",
    status: "backlog",
    priority: "medium",
    due_at: "2026-09-25T15:00:00Z",
    created_by: "usr-priya",
    created_at: "2026-09-18T14:00:00Z",
    updated_at: "2026-09-18T14:00:00Z",
  },
  {
    id: "task-37",
    event_id: "event-techfest-2026",
    title: "Audit Fire Extinguishers in Robotics Pit Area",
    description: "Verify 4 CO2 and dry-chemical fire extinguishers are unexpired in pit zone.",
    owner_id: "usr-tanvi",
    status: "done",
    priority: "high",
    due_at: "2026-09-16T15:00:00Z",
    created_by: "usr-prins",
    created_at: "2026-09-12T10:00:00Z",
    updated_at: "2026-09-16T14:30:00Z",
  },
  {
    id: "task-38",
    event_id: "event-techfest-2026",
    title: "Setup Sponsor Booth Backdrops in Hallway",
    description: "Allocate 3m x 3m display booths with 15A power socket for 6 tech sponsors.",
    owner_id: "usr-aarav",
    status: "todo",
    priority: "medium",
    due_at: "2026-09-24T18:00:00Z",
    created_by: "usr-priya",
    created_at: "2026-09-18T15:30:00Z",
    updated_at: "2026-09-18T15:30:00Z",
  },
  {
    id: "task-39",
    event_id: "event-techfest-2026",
    title: "Setup Drone Filming Permissions with Campus Airspace",
    description: "Obtain campus safety clearance for outdoor obstacle racing drone footage.",
    owner_id: "usr-neha",
    status: "done",
    priority: "low",
    due_at: "2026-09-14T17:00:00Z",
    created_by: "usr-jay",
    created_at: "2026-09-10T14:00:00Z",
    updated_at: "2026-09-14T16:00:00Z",
  },
  {
    id: "task-40",
    event_id: "event-techfest-2026",
    title: "Program LED Matrix Welcome Display at Main Gate",
    description: "Scroll live event schedule, countdown timer, and sponsor logos on gate ticker.",
    owner_id: "usr-siddharth",
    status: "in_progress",
    priority: "low",
    due_at: "2026-09-24T14:00:00Z",
    created_by: "usr-dev",
    created_at: "2026-09-18T12:00:00Z",
    updated_at: "2026-09-18T17:00:00Z",
  },
  {
    id: "task-41",
    event_id: "event-techfest-2026",
    title: "Create Final Volunteer WhatsApp & Radio Dispatch Channels",
    description: "Assign 8 walkie-talkie channels (Lead, Medical, Stage, Security, Catering, Tech).",
    owner_id: "usr-jay",
    status: "done",
    priority: "medium",
    due_at: "2026-09-15T18:00:00Z",
    created_by: "usr-prins",
    created_at: "2026-09-08T10:00:00Z",
    updated_at: "2026-09-15T17:00:00Z",
  },
  {
    id: "task-42",
    event_id: "event-techfest-2026",
    title: "Execute Post-Event Garbage Cleanup & Hall Handover",
    description: "Sort dry/wet recycling and complete damage walkthrough inspection with facility manager.",
    owner_id: "usr-tanvi",
    status: "backlog",
    priority: "low",
    due_at: "2026-10-27T12:00:00Z",
    created_by: "usr-prins",
    created_at: "2026-09-18T16:00:00Z",
    updated_at: "2026-09-18T16:00:00Z",
  },
];

// Seed Risks
export const SEED_RISKS: Risk[] = [
  {
    id: "risk-01",
    event_id: "event-techfest-2026",
    title: "Grand Auditorium Venue Booking Overdue",
    description: "Administrative signoff and key handover is 2 days overdue, actively blocking downstream stage rigging, lighting setup, and dress rehearsal.",
    severity: "critical",
    probability: "high",
    impact: "high",
    status: "active",
    source_type: "dependency",
    source_id: "task-01",
    evidence: "Task #task-01 is marked BLOCKED and was due on 2026-09-17 (2 days ago). 3 downstream tasks (task-02, task-03, task-04) cannot start.",
    suggested_action: "Escalate immediately to Faculty Coordinator Prof. Dave to expedite the Dean's endorsement stamp today.",
    affected_tasks: ["task-01", "task-02", "task-03", "task-04"],
    created_at: "2026-09-18T08:00:00Z",
  },
  {
    id: "risk-02",
    event_id: "event-techfest-2026",
    title: "Volunteer Rahul Sharma Critically Overloaded",
    description: "Rahul Sharma is assigned 7 active tasks including stage rigging, venue booking, and electrical procurement, exceeding safe operating capacity.",
    severity: "high",
    probability: "high",
    impact: "medium",
    status: "active",
    source_type: "volunteer",
    source_id: "usr-rahul",
    evidence: "Volunteer workload score is 92%. Assigned 7 tasks across 3 departments with 2 overlapping critical deadlines.",
    suggested_action: "Reassign 'Procure Heavy Extension Boards' to Arjun Pillai and 'Stage Rigging' to Rohit Nair.",
    affected_tasks: ["task-01", "task-02", "task-07", "task-08", "task-09", "task-10", "task-11"],
    created_at: "2026-09-18T09:30:00Z",
  },
  {
    id: "risk-03",
    event_id: "event-techfest-2026",
    title: "Title Sponsorship Packet Dispatch Delayed",
    description: "Outreach to tier-1 technology corporate sponsors is delayed by 48 hours, threatening budget solvency for keynotes.",
    severity: "high",
    probability: "medium",
    impact: "high",
    status: "active",
    source_type: "task",
    source_id: "task-05",
    evidence: "Task #task-05 was due on 2026-09-17. Title sponsor funds represent 40% of the target ₹15,00,000 budget.",
    suggested_action: "Send pre-approved executive sponsorship deck to alumni corporate contacts immediately.",
    affected_tasks: ["task-05"],
    created_at: "2026-09-18T10:15:00Z",
  },
  {
    id: "risk-04",
    event_id: "event-techfest-2026",
    title: "Catering Deposit Overdue - Penalty Warning",
    description: "The 30% advance deposit for 500 meals has not been released, risking vendor cancellation or price escalation.",
    severity: "medium",
    probability: "medium",
    impact: "medium",
    status: "active",
    source_type: "task",
    source_id: "task-06",
    evidence: "GreenPlate Hospitality terms specify cancellation if deposit is unpaid 30 days before event date.",
    suggested_action: "Authorize student council treasury release for ₹1,20,000 catering advance.",
    affected_tasks: ["task-06"],
    created_at: "2026-09-18T11:00:00Z",
  },
];

// Seed Documents with Chunks for Permission-Aware RAG
export const SEED_DOCUMENTS: Document[] = [
  {
    id: "doc-sponsorship-policy",
    club_id: "club-syntax-squad",
    event_id: "event-techfest-2026",
    name: "LJ_TechFest_2026_Sponsorship_Policy.pdf",
    storage_path: "/docs/sponsorship_policy.pdf",
    mime_type: "application/pdf",
    uploaded_by: "usr-prins",
    visibility: "organizer",
    created_at: "2026-08-15T10:00:00Z",
    chunk_count: 3,
  },
  {
    id: "doc-code-of-conduct",
    club_id: "club-syntax-squad",
    event_id: "event-techfest-2026",
    name: "LJ_TechFest_2026_Code_of_Conduct_and_Rules.pdf",
    storage_path: "/docs/code_of_conduct.pdf",
    mime_type: "application/pdf",
    uploaded_by: "usr-prins",
    visibility: "public",
    created_at: "2026-08-16T11:00:00Z",
    chunk_count: 2,
  },
  {
    id: "doc-venue-guidelines",
    club_id: "club-syntax-squad",
    event_id: "event-techfest-2026",
    name: "LJ_TechFest_2026_Venue_Access_Guidelines.pdf",
    storage_path: "/docs/venue_access.pdf",
    mime_type: "application/pdf",
    uploaded_by: "usr-jay",
    visibility: "volunteer",
    created_at: "2026-08-20T09:00:00Z",
    chunk_count: 2,
  },
];

export const SEED_DOCUMENT_CHUNKS: DocumentChunk[] = [
  {
    id: "chunk-spon-1",
    document_id: "doc-sponsorship-policy",
    chunk_index: 0,
    content: "Sponsorship Approval Requirements & Hierarchy: All corporate sponsorship contracts exceeding ₹1,00,000 require dual sign-off from the Faculty Coordinator (Prof. Dave) and the Club President (Prins Patel). Sponsorship deliverables must include logo placement on all stage banners, 3 complimentary VIP keynote passes, and a dedicated 3m x 3m networking booth in Engineering Hall B. Funds must be received via university bank transfer at least 14 days prior to event inauguration.",
    metadata: {
      club_id: "club-syntax-squad",
      event_id: "event-techfest-2026",
      document_name: "LJ_TechFest_2026_Sponsorship_Policy.pdf",
      visibility: "organizer",
      section: "Section 3.1: Approval Workflow & Deliverables",
    },
  },
  {
    id: "chunk-spon-2",
    document_id: "doc-sponsorship-policy",
    chunk_index: 1,
    content: "Tier Specifications: Title Sponsor (₹5,00,000) receives 15-minute keynote address slot, top logo prominence on all 500 attendee t-shirts, exclusive title naming rights ('LJ TechFest presented by Sponsor'), and full resume book of hackathon participants. Gold Sponsor (₹2,50,000) receives 5-minute pre-keynote address, logo on lanyards, and booth space. Silver Sponsor (₹1,00,000) receives logo on website and social media acknowledgement.",
    metadata: {
      club_id: "club-syntax-squad",
      event_id: "event-techfest-2026",
      document_name: "LJ_TechFest_2026_Sponsorship_Policy.pdf",
      visibility: "organizer",
      section: "Section 2.0: Tier Benefits Matrix",
    },
  },
  {
    id: "chunk-coc-1",
    document_id: "doc-code-of-conduct",
    chunk_index: 0,
    content: "Hackathon Eligibility & Team Rules: Teams must consist of 2 to 4 registered college students with valid student ID cards. Cross-college teams are permitted. All code submitted for judging must be written during the official 24-hour hackathon window starting Oct 24, 11:00 AM and ending Oct 25, 11:00 AM. Pre-existing open source libraries and public APIs are permitted, but core application logic must be newly authored.",
    metadata: {
      club_id: "club-syntax-squad",
      event_id: "event-techfest-2026",
      document_name: "LJ_TechFest_2026_Code_of_Conduct_and_Rules.pdf",
      visibility: "public",
      section: "Section 1.2: Team Composition & Code Integrity",
    },
  },
  {
    id: "chunk-venue-1",
    document_id: "doc-venue-guidelines",
    chunk_index: 0,
    content: "Grand Auditorium Safety & Decibel Restrictions: Sound pressure levels must not exceed 85 dBA continuous during daytime sessions and 70 dBA after 10:00 PM. No open flames, pyrotechnics, or smoke generators are permitted on stage without written fire department endorsement. All heavy electrical cabling across walkways must be covered by industrial yellow rubber cable protectors.",
    metadata: {
      club_id: "club-syntax-squad",
      event_id: "event-techfest-2026",
      document_name: "LJ_TechFest_2026_Venue_Access_Guidelines.pdf",
      visibility: "volunteer",
      section: "Section 4: Acoustic & Electrical Safety Rules",
    },
  },
];

// Seed Meetings & Transcripts
export const SEED_MEETINGS: Meeting[] = [
  {
    id: "meeting-core-sync-01",
    event_id: "event-techfest-2026",
    title: "LJ TechFest Core Team Sync - Sprint Review",
    scheduled_at: "2026-09-18T15:00:00Z",
    transcript_status: "processed",
    transcript_text: `Jay: Hey team, thanks for jumping in. Let's do a fast sync on urgent deliverables.
Priya: The Instagram teaser reel is in final review. I need to make sure we publish tomorrow morning by 10 AM to get weekend engagement.
Jay: Perfect, make sure you tag our title partners once approved. Also, Jay will finish the registration website by Friday so we can open hacker signups over the weekend.
Rahul: I visited Dean Office yesterday for the Grand Auditorium key handover, but the dean was in an academic council meeting. I'm going back tomorrow morning to get the physical stamped letter.
Jay: Rahul, that booking is critical—without it, the lighting truss and audio setup are blocked. Once that's confirmed, coordinate with Rohit for the sound check.
Priya: Also, we need someone to draft the emergency paramedic roster with Tanvi by Sunday.
Jay: Agreed. Let's record these action items and push them to ClubOps tasks immediately.`,
    action_items_count: 3,
  },
  {
    id: "meeting-core-sync-02",
    event_id: "event-techfest-2026",
    title: "Sponsorship & Budget Committee Meeting",
    scheduled_at: "2026-09-16T16:00:00Z",
    transcript_status: "processed",
    transcript_text: `Prins: We reviewed the sponsor pipeline. Aarav will send the updated tier-1 proposals to Google Cloud and RedBull by tonight.
Priya: Karan must release the 30% catering deposit to GreenPlate Hospitality before Friday to lock in the 500 meal package.
Jay: Noted. Let's keep financial compliance strictly logged.`,
    action_items_count: 2,
  },
];

export const SEED_ACTION_ITEMS: MeetingActionItem[] = [
  {
    id: "act-1",
    meeting_id: "meeting-core-sync-01",
    extracted_title: "Finish and launch registration website",
    owner_name: "Jay Shah",
    owner_id: "usr-jay",
    due_at: "2026-09-20T23:59:00Z",
    priority: "high",
    confidence: 0.96,
    approved: true,
  },
  {
    id: "act-2",
    meeting_id: "meeting-core-sync-01",
    extracted_title: "Publish Instagram teaser campaign and reels",
    owner_name: "Priya Mehta",
    owner_id: "usr-priya",
    due_at: "2026-09-19T10:00:00Z",
    priority: "high",
    confidence: 0.94,
    approved: true,
  },
  {
    id: "act-3",
    meeting_id: "meeting-core-sync-01",
    extracted_title: "Obtain stamped Grand Auditorium booking letter from Dean Office",
    owner_name: "Rahul Sharma",
    owner_id: "usr-rahul",
    due_at: "2026-09-19T12:00:00Z",
    priority: "critical",
    confidence: 0.98,
    approved: true,
  },
];

// Seed Announcements
export const SEED_ANNOUNCEMENTS: Announcement[] = [
  {
    id: "ann-01",
    event_id: "event-techfest-2026",
    title: "LJ TechFest 2026 Hackathon Registrations Opening Soon!",
    body: "Get ready! The 24-Hour AI & Robotics National Hackathon registrations go live this Friday at 6:00 PM. ₹2,50,000 prize pool, free meals, exclusive swags, and internship fast-tracks await.",
    status: "published",
    scheduled_at: "2026-09-15T12:00:00Z",
    created_by: "usr-prins",
    created_at: "2026-09-15T11:45:00Z",
  },
  {
    id: "ann-02",
    event_id: "event-techfest-2026",
    title: "Mandatory Volunteer Orientation on Saturday",
    body: "All 24 student volunteers must assemble at Engineering Hall B at 3:00 PM this Saturday for walkie-talkie distribution, security assignments, and shift roaster review.",
    status: "published",
    scheduled_at: "2026-09-17T09:00:00Z",
    created_by: "usr-jay",
    created_at: "2026-09-17T08:30:00Z",
  },
];

// Seed Notifications
export const SEED_NOTIFICATIONS: Notification[] = [
  {
    id: "notif-01",
    user_id: "usr-prins",
    type: "risk",
    title: "Critical Risk Detected: Auditorium Booking Delayed",
    body: "Task #task-01 is 2 days overdue and stalling 3 downstream staging tasks.",
    read_at: undefined,
    created_at: "2026-09-18T08:05:00Z",
  },
  {
    id: "notif-02",
    user_id: "usr-prins",
    type: "ai_approval",
    title: "AI Action Approved",
    body: "Prins Patel approved AI action: CREATE_TASK 'Obtain stamped booking letter'.",
    read_at: "2026-09-18T16:00:00Z",
    created_at: "2026-09-18T15:30:00Z",
  },
  {
    id: "notif-03",
    user_id: "usr-jay",
    type: "task",
    title: "Task Assigned: Launch Registration Portal",
    body: "You have been assigned to launch the portal by Friday night.",
    read_at: undefined,
    created_at: "2026-09-18T15:35:00Z",
  },
];

// Seed Audit Logs
export const SEED_AUDIT_LOGS: AuditLog[] = [
  {
    id: "audit-01",
    club_id: "club-syntax-squad",
    actor_user_id: "usr-prins",
    actor_type: "user",
    action: "CREATE_EVENT",
    entity_type: "event",
    entity_id: "event-techfest-2026",
    metadata_json: { event_name: "LJ TechFest 2026", budget: 15000 },
    created_at: "2026-08-01T10:00:00Z",
  },
  {
    id: "audit-02",
    club_id: "club-syntax-squad",
    actor_user_id: "usr-prins",
    actor_type: "ai",
    action: "EXTRACT_MEETING_ACTIONS",
    entity_type: "meeting",
    entity_id: "meeting-core-sync-01",
    metadata_json: { extracted_count: 3, model: "gemini-1.5-pro", confidence_avg: 0.96 },
    created_at: "2026-09-18T15:05:00Z",
  },
  {
    id: "audit-03",
    club_id: "club-syntax-squad",
    actor_user_id: "usr-prins",
    actor_type: "user",
    action: "APPROVE_AI_ACTION",
    entity_type: "ai_tool_call",
    entity_id: "tool-call-sample-01",
    metadata_json: {
      tool: "create_task",
      target: "Rahul Sharma",
      title: "Obtain stamped Grand Auditorium booking letter from Dean Office",
      status: "SUCCESS",
    },
    created_at: "2026-09-18T15:10:00Z",
  },
  {
    id: "audit-04",
    club_id: "club-syntax-squad",
    actor_user_id: "usr-jay",
    actor_type: "user",
    action: "UPDATE_TASK_STATUS",
    entity_type: "task",
    entity_id: "task-01",
    metadata_json: { old_status: "todo", new_status: "blocked", reason: "Dean absent from office" },
    created_at: "2026-09-18T16:00:00Z",
  },
];
